site_name: Programació d'Intel·ligència Artificial - CE Big Data i IA
docs_dir: "md"
site_dir: "docs"

#nav:
# - Unitat 1. Introducció a la Programació:
#   - 1. Algorismes i llenguatges: U01 Introducció a la programació/01_Algorismes_Llenguatges.md
#   - 2. Exercici pràctic: U01 Introducció a la programació/Exercici.md
# - Unitat 2. El llenguatge Python: 
#    - 1. Preparació de l'entorn: U02 Python/01_Entorns_i_projectes.md
#    - 2. Tipus de Dades. Operadors: U02 Python/02_Tipus_Variables_Operadors.md
#    - 3. Estructures de control: U02 Python/03_Estructures_de_control.md
#    - 4. Funcions: U02 Python/04_Funcions.md
#    - 5. Estructures de dades: U02 Python/05_Estructures_de_dades.md
#    - 6. Programació orientada a objectes: U02 Python/06_POO.md
#    - 7. Projecte: U02 Python/07_Projecte.md
#    - 8. Exercici pre projecte guiat: U02 Python/08_ExerciciPreProjecte.md
#    - 9. Annex I - Tractament de fitxers i carpetes amb python: U02 Python/09_Tractament_de_fitxer.md
# - Unitat 3. Python aplicat al Big Data i Intel·ligencia Artificial: 
#   - Teoria:
#     - 1. Introducció: U03 Python aplicat al Big Data i Intel·ligencia Artificial/0. Index.md
#     - 2. Manipulació de Dades amb Numpy: U03 Python aplicat al Big Data i Intel·ligencia Artificial/1. NumPy.md
#     - 3. Manipulació de Dades amb Pandas: U03 Python aplicat al Big Data i Intel·ligencia Artificial/02_Pandas.ipynb
#     - 4. Visualització de dades amb Matplotlib i Seaborn: U03 Python aplicat al Big Data i Intel·ligencia Artificial/03_Matplotlib-Seaborn.ipynb
#     - 5. Introducció al Machine Learning amb Scikit-Learn: U03 Python aplicat al Big Data i Intel·ligencia Artificial/04_Sklearn.ipynb
# #   - 6. Introducció al DeepLearning amb Keras: U03 Python aplicat al Big Data i Intel·ligencia Artificial/5. Keras.md
#   - Tasques:
#     - 2. NumPy:
#       - 1. Activitats: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/numpy/01_numpy.ipynb
#       - 2. Pràctiques: 
#         - 1. Mario: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/numpy/02_mario.ipynb
#         - 2. Derivades: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/numpy/03_derivades.ipynb
#         - 3. Vi: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/numpy/04_vi.ipynb
#         - 4. KNN: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/numpy/05_KNN.ipynb
#     - 3. Pandas:
#       - 1. Activitats:
#         - 1. Creacio: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/pandas/01_creacio.ipynb
#         - 2. Indexació, Selecció i Assignació: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/pandas/02_indexacio_seleccio_assignacio.ipynb
#         - 3. Resum i mapatge: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/pandas/03_resum_mapatge.ipynb
#         - 4. Agrupaments i ordenació: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/pandas/04_agrupament_i_ordenacio.ipynb
#         - 5. Dades i valors nuls: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/pandas/05_tipus_de_dades_i_valors_nulls.ipynb
#         - 6. Renombrat i combinació: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/pandas/06_renombrat_i_combinacio.ipynb
#       - 2. Pràctiques: 
#         - 1. Vendes: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/pandas/01_practica_vendes.ipynb
#         - 2. Dades categòriques: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/pandas/02_practica_dades_categoriques.ipynb
#     - 4. Matplotlib i Seaborn:
#       - 1. Activitats:
#         - 1. Gràfics de línies: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/seaborn/01_linecharts.ipynb
#         - 2. Gràfics de barres i mapes de calor: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/seaborn/02_bars_heatmaps.ipynb
#         - 3. Gràfics de dispersió: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/seaborn/03_scatters.ipynb
#         - 4. Distibucions: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/seaborn/04_distributions.ipynb
#     - 5. Sklearn:
#       - 1. Activitats:
#         - 1. Contrucció del model: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/sklearn/01_model.ipynb
#         - 2. Validació del model: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/sklearn/02_validacio.ipynb
#       - 2. Pràctiques:
#         - 1. Comparació de models: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/sklearn/03_comparacio_de_models.ipynb
#         - 2. Ajust de models: U03 Python aplicat al Big Data i Intel·ligencia Artificial/exercicis/sklearn/04_overfitting_underfitting.ipynb

nav: 
  - Unitat 4. Programació d'aplicacions: 
    - 2. Contenidors. Bases de Dades: U04 Programació d'Aplicacions/2. Contenidors de BBDD amb Docker.md
    - 3. Peticions HTTP. API REST: U04 Programació d'Aplicacions/3. Peticions HTTP. API-REST.md
    - 4. Servidors amb Flask: U04 Programació d'Aplicacions/4. Servidors amb Flask.md
  - Unitat 5. Programació d'aplicacions d'IA: 
    - 1. Azure Text:  U05 Programació d'Apps d'IA/01_AzureTextAnalytics.md
    - 2. Azure Face:  U05 Programació d'Apps d'IA/02_FaceDetection.md
    - 3. Computer Vision:  U05 Programació d'Apps d'IA/03_ComputerVision.md
  - Unitat 6. Convergència tecnològica: 
    - 1. Computer Vision:  U06 Convergencia tecnologica/01_OpenCV.md
  - Informació general:
    - Guia didàctica: info/guia_didactica.md

markdown_extensions: 
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji: 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme: 
  name: material
  logo: img/jaume.png
  favicon: img/jaume.png
  language: ca 
  palette:
#    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
#    - navigation.tabs         # afig dalt de tot una barra de navegació
    - navigation.footer       # footer de la pagina
    - navigation.top          # botó flotant de retorn a arriba


copyright: Copyright &copy; 2023 - Joan Gerard Camarena & Ferran Cunyat


extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:jg.camarenaestruch@edu.gva.es
      name: Joan Gerard Camarena
    - icon: fontawesome/solid/paper-plane
      link: mailto:f.cunyatpellicer@edu.gva.es
      name: Ferran Cunyat

plugins:
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
         #  execute: true
    #  execute_ignore:
    #     - "*.py"
     # No revisa aquestes carpetes
  - exclude:   # https://github.com/apenwarr/mkdocs-exclude
      glob:
        - "*.ipynb"
        - "*.py"

     
#  - pdf-export